# fluent-bit-http-input-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-http-input
  namespace: logging
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fluent-bit
  ports:
    - name: http-input
      port: 9880
      targetPort: 9880
      protocol: TCP

