loki:
  auth_enabled: false
  ingester_client:
    remote_timeout: 10s  # Increase from default 1s
  server:
    http_server_write_timeout: 600s
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    filesystem:
      directory: /tmp/loki/chunks
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  ruler:
    enable_api: true
  auth_enabled: false

#deploymentMode: Distributed  # Distributed is used on microservice mode

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    storageClass: standard  #gp2
    accessModes:
      - ReadWriteOnce
    size: 2Gi

  resources:
    requests:
      cpu: 500m
      memory: 521Mi
    limits:
      cpu: "1"
      memory: "1Gi"

sidecar:
  image:
    repository: kiwigrid/k8s-sidecar
    tag: 1.30.0
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

chunksCache:
  allocatedMemory: 500

# This exposes the Loki gateway so it can be written to and queried externaly if LB is used, or use NodePort for cluster
# By default the URL will be http://loki-gateway/loki/api/
#
gateway:
  enabled: false
  basicAuth:
    enabled: false
      #existingSecret: loki-gateway-auth
    username: admin
    password: admin   


  ingress:
    enabled: true
    hosts:
      - host: loki-gateway.logging.svc.cluster.local
        paths:
          - path: /
            pathType: Prefix

# Enable minio for storage if object_store is s3
minio:
  enabled: false

promtail:
  enabled: true
  scrape_configs:
    - job_name: minio-tenant-logs
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        # Select only pods in minio tenant namespace
        - source_labels: [__meta_kubernetes_namespace]
          action: keep
          regex: minio-tenant-beta
        # Filter to pods matching MinIO tenant labels
        - source_labels: [__meta_kubernetes_pod_label_v1_min_io_tenant]
          action: keep
          regex: tenant-beta
      pipeline_stages:
        - docker: {}
      # (Optional) Add further label or line processing as needed
