apiVersion: v1
kind: Secret
metadata:
  name: loki-gateway-auth
  namespace: logging
type: Opaque
stringData:
  .htpasswd: |
    admin:$apr1$NtuT9LtX$PNHRpDhmQvns.SRoCEW6//  # (copy the full htpasswd content here)

